
theme = "solarized-dark"
icons = "awesome"


[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "pacman"
interval = 60
format = "{count} updates available"
format_singular = "{count} update available"
format_up_to_date = "fully updated"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
